name: Generate Keystore (Temporary)

on:
  workflow_dispatch: # لكي نشغله يدوياً

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore File
        run: |
          # إنشاء المفتاح بكلمة مرور 12345678 واسم alshehab
          keytool -genkey -v -keystore alshehab.jks -keyalg RSA -keysize 2048 -validity 10000 -alias alshehab -storepass 12345678 -keypass 12345678 -dname "CN=Alshehab, OU=App, O=Alshehab, L=City, S=State, C=US"
          
          # تحويل الملف إلى نص Base64 وحفظه في ملف نصي
          base64 alshehab.jks > keystore_base64.txt

      - name: Upload Base64 Text
        uses: actions/upload-artifact@v4
        with:
          name: keystore-secret-text
          path: keystore_base64.txt
          
